In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [6]:
b = [1,2,3]
print(b)
b

[1, 2, 3]


[1, 2, 3]

In [10]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
c

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
d=np.array([[1,2,3,4],[5,6,7,8]])
print(d)
d

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
nb=np.zeros(4)
print(nb)

[0. 0. 0. 0.]


In [13]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.arange(0,10,2) #start, stop, step

array([0, 2, 4, 6, 8])

## Add, Remove, Sort

In [21]:
a = np.arange(3,10,2)
b = np.ones(3)

c= np.append(a,b)
print(c)

[3. 5. 7. 9. 1. 1. 1.]


In [26]:
e=np.delete(c,5)
print(e)

[3. 5. 7. 9. 1. 1.]


In [27]:
d = np.sort(e)
print(d)

[1. 1. 3. 5. 7. 9.]


## Shape n Size

In [30]:
ab = np.array([[[1,2,3,4],
              [5,6,7,8]],
             [[11,22,33,44],
             [55,66,77,88]]])

np.ndim(ab)

3

In [31]:
np.size(ab)

16

In [32]:
np.shape(ab) #kita akan dapat (2,2,4) artinya :
#di level pertama ada 2 element
#setiap item tersebut(level ke-2) ada 2 item
#setap element tersebut(level ke-3) ada 4 barang lagi

(2, 2, 4)

## Reshape

In [36]:
array_asal = np.arange(1,25,1)
print(array_asal)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [38]:
array_b=array_asal.reshape(4,6)
print(array_b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [40]:
array_c=array_asal.reshape(2,3,4)
print(array_c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [41]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [44]:
a2=a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [46]:
row_vector = a[np.newaxis, :] #nambah kolom
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [47]:
col_vector=a[:,np.newaxis] #nambah row
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [49]:
b=np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [51]:
c=np.expand_dims(b, axis=0)
print(c.shape)
print(c)

(1, 6, 1)
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]


In [53]:
data=np.array([1,2,3])
print(data)
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
2
[1 2]
[2 3]
[2 3]


In [54]:
array_asal

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [55]:
array_asal[array_asal >20]

array([21, 22, 23, 24])

In [56]:
kondisi = (array_asal>19)
array_asal[kondisi]

array([20, 21, 22, 23, 24])

In [57]:
modulo2 = (array_asal%2==0)
array_asal[modulo2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [64]:
kondisi2=array_asal[(array_asal>=10) & (array_asal%3==0)]
print(kondisi2)

[12 15 18 21 24]


In [73]:
arr=np.array([[1,2],[3,4],[5,6]])
arr1=np.array([[10,20],[30,40],[50,60]])
arr2=np.vstack((arr,arr1))
print(arr2)
arr3=np.hstack((arr1,arr))
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [30 40]
 [50 60]]
[[10 20  1  2]
 [30 40  3  4]
 [50 60  5  6]]


In [76]:
np.vsplit(arr3,3)

[array([[10, 20,  1,  2]]),
 array([[30, 40,  3,  4]]),
 array([[50, 60,  5,  6]])]

In [80]:
np.hsplit(arr2, 2)

[array([[ 1],
        [ 3],
        [ 5],
        [10],
        [30],
        [50]]),
 array([[ 2],
        [ 4],
        [ 6],
        [20],
        [40],
        [60]])]